/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagementsystem;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author williamqin
 */
public class MainView extends javax.swing.JFrame {
    
    // METHODS
    
    /**
     * Creates new form MainInterface
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonOpen = new javax.swing.JButton();
        panelViewEmp = new javax.swing.JPanel();
        labelViewTitle = new javax.swing.JLabel();
        panelEmp = new javax.swing.JPanel();
        labelEmpSubtitle = new javax.swing.JLabel();
        labelEmpNum = new javax.swing.JLabel();
        labelVarEmpNum = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        labelVarFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        labelVarLastName = new javax.swing.JLabel();
        labelSex = new javax.swing.JLabel();
        labelVarSex = new javax.swing.JLabel();
        labelWorkLocation = new javax.swing.JLabel();
        labelVarWorkLoc = new javax.swing.JLabel();
        labelPayrollSubtitle = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();
        labelVarType = new javax.swing.JLabel();
        labelDeductRate = new javax.swing.JLabel();
        labelVarDeductRate = new javax.swing.JLabel();
        labelIncome = new javax.swing.JLabel();
        labelVarIncome = new javax.swing.JLabel();
        labelHoursPerWeek = new javax.swing.JLabel();
        labelVarHoursPerWeek = new javax.swing.JLabel();
        labelWeeksPerYear = new javax.swing.JLabel();
        labelVarWeeksPerYear = new javax.swing.JLabel();
        labelGrossIncome = new javax.swing.JLabel();
        labelVarGrossIncome = new javax.swing.JLabel();
        labelDeduction = new javax.swing.JLabel();
        labelVarDeduction = new javax.swing.JLabel();
        labelNetIncome = new javax.swing.JLabel();
        labelVarNetIncome = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        panelDatabase = new javax.swing.JPanel();
        labelViewTitle1 = new javax.swing.JLabel();
        labelSearch = new javax.swing.JLabel();
        scrollPaneDatabase = new javax.swing.JScrollPane();
        tableDatabase = new javax.swing.JTable();
        fieldSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        comboBoxSearchType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        labelTitle.setText("Employee Database");
        labelTitle.setToolTipText("");

        buttonAdd.setText("Add New Employee");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonOpen.setText("Open");
        buttonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        panelViewEmp.setEnabled(false);

        labelViewTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelViewTitle.setText("View Employee");
        labelViewTitle.setToolTipText("");

        panelEmp.setBackground(new java.awt.Color(204, 204, 204));

        labelEmpSubtitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelEmpSubtitle.setText("Employee Information");
        labelEmpSubtitle.setToolTipText("");

        labelEmpNum.setText("Employee Number");

        labelVarEmpNum.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarEmpNum.setText("Select an employee...");

        labelFirstName.setText("First Name");

        labelVarFirstName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarFirstName.setText(" ");
        labelVarFirstName.setAutoscrolls(true);
        labelVarFirstName.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarFirstName.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarFirstName.setPreferredSize(new java.awt.Dimension(210, 16));

        labelLastName.setText("Last Name");

        labelVarLastName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarLastName.setText(" ");
        labelVarLastName.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarLastName.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarLastName.setPreferredSize(new java.awt.Dimension(210, 16));

        labelSex.setText("Sex");

        labelVarSex.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarSex.setText(" ");
        labelVarSex.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarSex.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarSex.setPreferredSize(new java.awt.Dimension(210, 16));

        labelWorkLocation.setText("Work Location");
        labelWorkLocation.setToolTipText("");

        labelVarWorkLoc.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarWorkLoc.setText(" ");
        labelVarWorkLoc.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarWorkLoc.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarWorkLoc.setPreferredSize(new java.awt.Dimension(210, 16));

        labelPayrollSubtitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelPayrollSubtitle.setText("Payroll Information");

        labelType.setText("Employement Type");

        labelVarType.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarType.setText(" ");
        labelVarType.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarType.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarType.setPreferredSize(new java.awt.Dimension(210, 16));

        labelDeductRate.setText("Deduction Rate");

        labelVarDeductRate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarDeductRate.setText("%");
        labelVarDeductRate.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarDeductRate.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarDeductRate.setPreferredSize(new java.awt.Dimension(210, 16));

        labelIncome.setText("Annual Salary");

        labelVarIncome.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarIncome.setText("$");
        labelVarIncome.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarIncome.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarIncome.setPreferredSize(new java.awt.Dimension(210, 16));

        labelHoursPerWeek.setText("Hours Per Week");
        labelHoursPerWeek.setEnabled(false);

        labelVarHoursPerWeek.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarHoursPerWeek.setText(" ");
        labelVarHoursPerWeek.setEnabled(false);
        labelVarHoursPerWeek.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarHoursPerWeek.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarHoursPerWeek.setPreferredSize(new java.awt.Dimension(210, 16));

        labelWeeksPerYear.setText("Weeks Per Year");
        labelWeeksPerYear.setEnabled(false);

        labelVarWeeksPerYear.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarWeeksPerYear.setText(" ");
        labelVarWeeksPerYear.setEnabled(false);
        labelVarWeeksPerYear.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarWeeksPerYear.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarWeeksPerYear.setPreferredSize(new java.awt.Dimension(210, 16));

        labelGrossIncome.setText("Gross Income");

        labelVarGrossIncome.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarGrossIncome.setText("$");
        labelVarGrossIncome.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarGrossIncome.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarGrossIncome.setPreferredSize(new java.awt.Dimension(210, 16));

        labelDeduction.setText("Deduction");

        labelVarDeduction.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarDeduction.setText("$");
        labelVarDeduction.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarDeduction.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarDeduction.setPreferredSize(new java.awt.Dimension(210, 16));

        labelNetIncome.setText("Net Income");

        labelVarNetIncome.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarNetIncome.setText("$");
        labelVarNetIncome.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarNetIncome.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarNetIncome.setPreferredSize(new java.awt.Dimension(210, 16));

        javax.swing.GroupLayout panelEmpLayout = new javax.swing.GroupLayout(panelEmp);
        panelEmp.setLayout(panelEmpLayout);
        panelEmpLayout.setHorizontalGroup(
            panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpLayout.createSequentialGroup()
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmpSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPayrollSubtitle))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelEmpLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEmpLayout.createSequentialGroup()
                                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelWorkLocation)
                                    .addComponent(labelLastName)
                                    .addComponent(labelSex)
                                    .addComponent(labelFirstName)
                                    .addComponent(labelEmpNum))
                                .addGap(47, 47, 47)
                                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelVarEmpNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelVarLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelVarFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelVarSex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelVarWorkLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panelEmpLayout.createSequentialGroup()
                                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelEmpLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelNetIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelHoursPerWeek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelGrossIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(12, 12, 12))
                                        .addGroup(panelEmpLayout.createSequentialGroup()
                                            .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelEmpLayout.createSequentialGroup()
                                                    .addComponent(labelDeductRate)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(labelIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(44, 44, 44)))
                                    .addGroup(panelEmpLayout.createSequentialGroup()
                                        .addComponent(labelType)
                                        .addGap(42, 42, 42)))
                                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelVarNetIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(labelVarDeduction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelVarGrossIncome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelVarWeeksPerYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(65, 65, 65))
                                    .addGroup(panelEmpLayout.createSequentialGroup()
                                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(labelVarHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(labelVarIncome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(labelVarDeductRate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(labelVarType, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        panelEmpLayout.setVerticalGroup(
            panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelEmpSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpNum)
                    .addComponent(labelVarEmpNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstName)
                    .addComponent(labelVarFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLastName)
                    .addComponent(labelVarLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSex)
                    .addComponent(labelVarSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVarWorkLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWorkLocation))
                .addGap(18, 18, 18)
                .addComponent(labelPayrollSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelType)
                    .addComponent(labelVarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDeductRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelVarDeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVarIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIncome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoursPerWeek)
                    .addComponent(labelVarHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWeeksPerYear)
                    .addComponent(labelVarWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGrossIncome)
                    .addComponent(labelVarGrossIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDeduction)
                    .addComponent(labelVarDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNetIncome)
                    .addComponent(labelVarNetIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonRemove.setText("Remove");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewEmpLayout = new javax.swing.GroupLayout(panelViewEmp);
        panelViewEmp.setLayout(panelViewEmpLayout);
        panelViewEmpLayout.setHorizontalGroup(
            panelViewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewEmpLayout.createSequentialGroup()
                .addGroup(panelViewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewEmpLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelViewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelViewEmpLayout.createSequentialGroup()
                                .addComponent(buttonRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelViewTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelViewEmpLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(panelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelViewEmpLayout.setVerticalGroup(
            panelViewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewEmpLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelViewTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        labelViewTitle1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelViewTitle1.setText("View Database");
        labelViewTitle1.setToolTipText("");

        labelSearch.setText("Search By:");

        tableDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp. Number", "Type", "First Name", "Last Name", "Work Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneDatabase.setViewportView(tableDatabase);
        if (tableDatabase.getColumnModel().getColumnCount() > 0) {
            tableDatabase.getColumnModel().getColumn(0).setPreferredWidth(90);
            tableDatabase.getColumnModel().getColumn(1).setPreferredWidth(80);
            tableDatabase.getColumnModel().getColumn(2).setPreferredWidth(80);
            tableDatabase.getColumnModel().getColumn(3).setPreferredWidth(80);
            tableDatabase.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        fieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSearchActionPerformed(evt);
            }
        });

        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        comboBoxSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show All", "Employee Number", "First Name", "Last Name", "Sex", "Work Location", "Full Time", "Part Time" }));

        javax.swing.GroupLayout panelDatabaseLayout = new javax.swing.GroupLayout(panelDatabase);
        panelDatabase.setLayout(panelDatabaseLayout);
        panelDatabaseLayout.setHorizontalGroup(
            panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatabaseLayout.createSequentialGroup()
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatabaseLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(labelViewTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(labelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxSearchType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatabaseLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDatabaseLayout.createSequentialGroup()
                                .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelDatabaseLayout.setVerticalGroup(
            panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatabaseLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelViewTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelViewEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelViewEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        
        InterfaceIO.getInstance().beginFormAddEmployee();
        
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        // TODO add your handling code here:
        
        InterfaceIO.getInstance().removeCurrentEmployee();
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        
        InterfaceIO.getInstance().editCurrentEmployee();
        
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        
        searchDatabase();
        
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void fieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSearchActionPerformed
        // TODO add your handling code here:
        
        buttonSearchActionPerformed(evt);
        
    }//GEN-LAST:event_fieldSearchActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        
        InterfaceIO.getInstance().saveDatabase();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenActionPerformed
        // TODO add your handling code here:
        
        InterfaceIO.getInstance().openDatabase();
    }//GEN-LAST:event_buttonOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    
    public void searchDatabase() {
        String type = comboBoxSearchType.getSelectedItem().toString();
        
        InterfaceIO.getInstance().searchEmployees(fieldSearch.getText(), type);
    }
   
    public void addRowToTable(Object[] row) {
        
        DefaultTableModel model = (DefaultTableModel) tableDatabase.getModel();
        model.addRow(row);
        tableDatabase.setModel(model);
        
    }
    
    public void clearTable() {
        
        DefaultTableModel model = (DefaultTableModel) tableDatabase.getModel();
        model.setRowCount(0);
        tableDatabase.setModel(model);
        
    }
    
    public void selectRow(int row) {
        
        tableDatabase.setRowSelectionInterval(row, row);
        
    }
    
    public javax.swing.JTable getTableDatabase() {
        return tableDatabase;
    }
    
    public void setVarEmpNum(int empNum, boolean isEmployee) {
        if (!isEmployee)
            labelVarEmpNum.setText("Select an employee...");
        else
            labelVarEmpNum.setText(String.valueOf(empNum));
    } 
    public void setVarFirstName(String firstName) {
        labelVarFirstName.setText(firstName);
    }
    public void setVarLastName(String lastName) {
        labelVarLastName.setText(lastName);
    }
    public void setVarSex(String sex) {
        labelVarSex.setText(sex);
    }
    public void setVarWorkLoc(String workLoc) {
        labelVarWorkLoc.setText(workLoc);
    }
    
    public void setVarEmploymentType(String type) {
        labelVarType.setText(type);
    }
    public void setVarDeductRate(double deductRate) {
        labelVarDeductRate.setText(String.format("%.2f", deductRate) + "%");
    }
    public void setVarIncome(double income) {
        labelVarIncome.setText("$" + String.format("%.2f", income));
    }
    public void setLabelIncome(String label) {
        labelIncome.setText(label);
    }
    public void setPartTimeLabels(boolean activate) {
        labelHoursPerWeek.setEnabled(activate);
        labelWeeksPerYear.setEnabled(activate);
        labelVarHoursPerWeek.setEnabled(activate);
        labelVarWeeksPerYear.setEnabled(activate);
    }
    public void setVarHoursPerWeek(double hoursPerWeek) {
        labelVarHoursPerWeek.setText(String.format("%.1f", hoursPerWeek));
    }
    public void setVarWeeksPerYear(double weeksPerYear) {
        labelVarWeeksPerYear.setText(String.format("%.1f", weeksPerYear));
    }
    public void setVarGrossIncome(double grossIncome) {
        labelVarGrossIncome.setText("$" + String.format("%.2f", grossIncome));
    }
    public void setVarDeduction(double deduction) {
        labelVarDeduction.setText("$" + String.format("%.2f", deduction));
    }
    public void setVarNetIncome(double netIncome) {
        labelVarNetIncome.setText("$" + String.format("%.2f", netIncome));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonOpen;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JComboBox<String> comboBoxSearchType;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JLabel labelDeductRate;
    private javax.swing.JLabel labelDeduction;
    private javax.swing.JLabel labelEmpNum;
    private javax.swing.JLabel labelEmpSubtitle;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelGrossIncome;
    private javax.swing.JLabel labelHoursPerWeek;
    private javax.swing.JLabel labelIncome;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelNetIncome;
    private javax.swing.JLabel labelPayrollSubtitle;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JLabel labelSex;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel labelVarDeductRate;
    private javax.swing.JLabel labelVarDeduction;
    private javax.swing.JLabel labelVarEmpNum;
    private javax.swing.JLabel labelVarFirstName;
    private javax.swing.JLabel labelVarGrossIncome;
    private javax.swing.JLabel labelVarHoursPerWeek;
    private javax.swing.JLabel labelVarIncome;
    private javax.swing.JLabel labelVarLastName;
    private javax.swing.JLabel labelVarNetIncome;
    private javax.swing.JLabel labelVarSex;
    private javax.swing.JLabel labelVarType;
    private javax.swing.JLabel labelVarWeeksPerYear;
    private javax.swing.JLabel labelVarWorkLoc;
    private javax.swing.JLabel labelViewTitle;
    private javax.swing.JLabel labelViewTitle1;
    private javax.swing.JLabel labelWeeksPerYear;
    private javax.swing.JLabel labelWorkLocation;
    private javax.swing.JPanel panelDatabase;
    private javax.swing.JPanel panelEmp;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelViewEmp;
    private javax.swing.JScrollPane scrollPaneDatabase;
    private javax.swing.JTable tableDatabase;
    // End of variables declaration//GEN-END:variables
}
